langauage:
    go

go:
    - master

install:
    - go get github.com/gohugoio/hugo

script:
    - hugo -t casper-two

deploy:
    local_dir: public
    repo: CyberSecNITD/CyberSecNITD.github.io
    target_branch: master
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
