baseurl         = "https://cybersecnitd.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "CyberSec NITD"
  subtitle    = "Cyber security club at NIT Delhi"

  cover       = ""
  description = "Face of NITD Cyber Security Club on the web"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "CyberSecNITD"

  logo = ""
  orgName = "CyberSec NITD"
  orgWebsite = "https://cybersecnitd.github.io"
  orgDescription = "Cyber security club at NIT Delhi"

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Events"
  url = "/events"
  weight = 100

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 99
