baseurl         = "https://cybersecnitd.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "CyberSec NITD"
  subtitle    = "Cyber security club at NIT Delhi"

  cover       = ""
  description = "Face of NITD Cyber Security Club on the web"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "CyberSecNITD"
  telegramLink = "https://t.me/joinchat/Ez80i0_cdc8cQv5IUceBzg"

  logo = ""
  orgName = "CyberSec NITD"
  orgWebsite = "https://cybersecnitd.github.io"
  orgDescription = "Cyber security club at NIT Delhi"

  author = "CyberSec NITD"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
	post = "/:slug/"
	segfault = "/segfault/:slug/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "Segfault"
    weight = 2
    url  = "/segfault/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
